run1:
		gcc -o lab2 main.c
		./lab2
run1v:
		gcc -o lab2 main.c
		valgrind ./lab2

run2:
		gcc -o lab2 main2.c
		./lab2 input.txt
run2v:
		gcc -o lab2 main2.c
		valgrind ./lab2 input.txt
clean:
		rm ./lab2
